export type Category = { id:string; slug:string; name:string; icon:string; color:string };
export type Business = { id:string; slug:string; name:string; categoryId:string; shortDescription:string; city:string; state:string; zone:string; rating:number|null; reviewCount:number; verified:boolean; featured:boolean; demoData:true; services:string[]; tags:string[]; sourceUrl:string; cover:string };
export const categories:Category[]=[
 {id:"food",slug:"restaurantes",name:"Restaurantes y cafeterías",icon:"Utensils",color:"#F06D4F"},{id:"health",slug:"salud",name:"Salud y servicios médicos",icon:"HeartPulse",color:"#22A06B"},{id:"auto",slug:"automotriz",name:"Automotriz",icon:"Car",color:"#3977D5"},{id:"shops",slug:"compras",name:"Compras y tiendas",icon:"ShoppingBag",color:"#9167C7"},{id:"wellness",slug:"bienestar",name:"Belleza, fitness y bienestar",icon:"Sparkles",color:"#DB5D91"}
];
const names:Record<string,string[]>={
 food:["La Casona","Mochomos Chihuahua","La Cabaña Smokehouse Haciendas","Cinco Panes","El Poeta Restaurante","Garufa Chihuahua","Akari Japanese Bistro","Great American Steakhouse Chihuahua"],
 health:["Hospital Ángeles Chihuahua","Star Médica Chihuahua","CHRISTUS MUGUERZA Hospital del Parque","Consultorios CHRISTUS MUGUERZA del Parque","Hospital Clínica del Centro","Hospital San Felipe","Salud Digna Chihuahua","Laboratorio Médico del Chopo Chihuahua"],
 auto:["Toyota Chihuahua","Mazda Chihuahua","Honda Visión Chihuahua","Nissan Jidosha Chihuahua","Kia Juventud","Chevrolet Toro","Ford Pasa Chihuahua","Volkswagen Autokam Chihuahua"],
 shops:["Alsuper","Liverpool Fashion Mall Chihuahua","Sears Fashion Mall Chihuahua","The Home Depot Chihuahua","Costco Chihuahua","Sam’s Club Chihuahua","Walmart Chihuahua","Office Depot Chihuahua"],
 wellness:["Smart Fit Distrito Uno","Smart Fit Cantera","Station 24 Fitness Chihuahua","Corner Sport Chihuahua","Anytime Fitness Chihuahua","Sephora Fashion Mall Chihuahua","Sally Beauty Chihuahua","Bellísima Fashion Mall Chihuahua"]};
const descriptions:Record<string,string>={food:"Sabores, experiencias y opciones para disfrutar cerca de ti.",health:"Atención y servicios de salud con información pública por confirmar.",auto:"Venta, servicio, mantenimiento, refacciones y cotización.",shops:"Productos, compras y soluciones para el hogar y la oficina.",wellness:"Bienestar, entrenamiento, belleza y cuidado personal."};
const services:Record<string,string[]>={food:["Desayunos","Comida","Para llevar"],health:["Consulta","Diagnóstico","Atención"],auto:["Servicio","Refacciones","Solicitar cotización"],shops:["Tienda","Recoger en sucursal","Atención"],wellness:["Membresías","Clases","Asesoría"]};
const zones=["Centro","Distrito Uno","Periférico de la Juventud","Haciendas","Fashion Mall"];
export const businesses:Business[]=categories.flatMap((cat,ci)=>names[cat.id].map((name,i)=>({id:`${cat.id}-${i+1}`,slug:name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,""),name,categoryId:cat.id,shortDescription:descriptions[cat.id],city:"Chihuahua",state:"Chihuahua",zone:zones[(i+ci)%zones.length],rating:cat.id==="health"?null:Number((4.2+(i%6)*.1).toFixed(1)),reviewCount:cat.id==="health"?0:18+i*13,verified:i%3===0,featured:i<2,demoData:true,services:services[cat.id],tags:[cat.slug,...services[cat.id],name],sourceUrl:"https://visitachihuahuacapital.com/",cover:`cover-${cat.id}-${(i%3)+1}`})));
export const promotions=[{id:"p1",business:"La Cabaña Smokehouse Haciendas",title:"10% de descuento de lunes a jueves",valid:"Vigente hasta 30 sep 2026",category:"food"},{id:"p2",business:"Mazda Chihuahua",title:"Revisión preventiva incluida",valid:"Vigente hasta 15 oct 2026",category:"auto"},{id:"p3",business:"Smart Fit Distrito Uno",title:"Inscripción sin costo",valid:"Vigente hasta 5 oct 2026",category:"wellness"},{id:"p4",business:"Office Depot Chihuahua",title:"Producto seleccionado con descuento",valid:"Vigente hasta 22 sep 2026",category:"shops"}];
export const activity=[{day:"1 sep",visits:44,contacts:8},{day:"5 sep",visits:58,contacts:11},{day:"9 sep",visits:50,contacts:9},{day:"13 sep",visits:72,contacts:14},{day:"17 sep",visits:83,contacts:18},{day:"21 sep",visits:76,contacts:15},{day:"25 sep",visits:96,contacts:22},{day:"30 sep",visits:112,contacts:26}];
